// This file is auto-generated by @hey-api/openapi-ts

export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'VIEW' | 'LOGIN' | 'LOGOUT' | 'EXPORT' | 'IMPORT';

export type AuditLogCreate = {
    action: AuditAction;
    resource_type: string;
    resource_id: string;
    user_agent?: (string | null);
    ip_address?: (string | null);
    before_state?: (string | null);
    after_state?: (string | null);
    custom_metadata?: (string | null);
    severity?: AuditSeverity;
    tenant_id?: (string | null);
};

export type AuditLogPublic = {
    action: AuditAction;
    resource_type: string;
    resource_id: string;
    user_agent?: (string | null);
    ip_address?: (string | null);
    before_state?: (string | null);
    after_state?: (string | null);
    custom_metadata?: (string | null);
    severity?: AuditSeverity;
    tenant_id?: (string | null);
    id: string;
    user_id: string;
    session_id: (string | null);
    timestamp: string;
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type AuditLogUpdate = {
    action?: (AuditAction | null);
    resource_type?: (string | null);
    resource_id?: (string | null);
    user_agent?: (string | null);
    ip_address?: (string | null);
    before_state?: (string | null);
    after_state?: (string | null);
    custom_metadata?: (string | null);
    severity?: (AuditSeverity | null);
    tenant_id?: (string | null);
};

export type AuditSeverity = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

export type Body_audit_logs_log_action = {
    before_state?: ({
    [key: string]: unknown;
} | null);
    after_state?: ({
    [key: string]: unknown;
} | null);
    custom_metadata?: ({
    [key: string]: unknown;
} | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuditLogsReadAuditLogsData = {
    action?: (AuditAction | null);
    endDate?: (string | null);
    limit?: number;
    resourceId?: (string | null);
    resourceType?: (string | null);
    severity?: (AuditSeverity | null);
    skip?: number;
    startDate?: (string | null);
    tenantId?: (string | null);
};

export type AuditLogsReadAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsCreateAuditLogData = {
    requestBody: AuditLogCreate;
};

export type AuditLogsCreateAuditLogResponse = (AuditLogPublic);

export type AuditLogsReadAuditLogData = {
    id: string;
};

export type AuditLogsReadAuditLogResponse = (AuditLogPublic);

export type AuditLogsUpdateAuditLogData = {
    id: string;
    requestBody: AuditLogUpdate;
};

export type AuditLogsUpdateAuditLogResponse = (AuditLogPublic);

export type AuditLogsDeleteAuditLogData = {
    id: string;
};

export type AuditLogsDeleteAuditLogResponse = (Message);

export type AuditLogsGetAuditStatsData = {
    endDate?: (string | null);
    startDate?: (string | null);
    tenantId?: (string | null);
};

export type AuditLogsGetAuditStatsResponse = ({
    [key: string]: unknown;
});

export type AuditLogsLogActionData = {
    action: AuditAction;
    requestBody?: Body_audit_logs_log_action;
    resourceId: string;
    resourceType: string;
    severity?: AuditSeverity;
    tenantId?: (string | null);
};

export type AuditLogsLogActionResponse = (AuditLogPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);